export interface GalleryLookbookItem {
  id: string;
  title: string;
  category: "MEN" | "WOMEN" | "KIDS" | "EDITORIAL";
  imageUrl: string;
  description: string;
  shoeModel: string;
  link: string;
  order: number;
  tags: string[];
  photographer?: string;
  location?: string;
  likes?: number;
}

export const CURATED_GALLERY_ITEMS: GalleryLookbookItem[] = [
  // =================== WOMEN'S COLLECTION ===================
  {
    id: "gal-women-1",
    title: "Paris Fashion Week — Sleek Metallic Aura",
    category: "WOMEN",
    imageUrl: "https://images.unsplash.com/photo-1515347619252-60a4bf4fff4f?w=1200&q=85",
    description: "Styled on the Paris runway paired with draped monochrome silk. Engineered with reflective carbon accents and featherlight nitrogen midsole.",
    shoeModel: "VELOCE AURA NITRO 02",
    link: "/category/running",
    order: 1,
    tags: ["Runway", "High Fashion", "Metallic", "Paris"],
    photographer: "Elena Rostova",
    location: "Palais de Tokyo, Paris",
    likes: 342,
  },
  {
    id: "gal-women-2",
    title: "Milan Boulevard — Cloud Luxe Soft Strider",
    category: "WOMEN",
    imageUrl: "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=1200&q=85",
    description: "Minimalist Italian leather trainer tailored for all-day urban movement with zero fatigue and cloud-soft step dynamics.",
    shoeModel: "VELOCE CLOUD WALK LUXE",
    link: "/category/lifestyle",
    order: 2,
    tags: ["Minimalist", "Streetwear", "Milan", "Leather"],
    photographer: "Matteo Bianchi",
    location: "Via Montenapoleone, Milan",
    likes: 289,
  },
  {
    id: "gal-women-3",
    title: "Brooklyn Sunset — Chroma Velocity",
    category: "WOMEN",
    imageUrl: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=1200&q=85",
    description: "Pastel gradient breathable mesh sneaker tailored for high-cadence evening tempo runs across the Williamsburg waterfront.",
    shoeModel: "VELOCE CHROMA STRIDER V1",
    link: "/category/running",
    order: 3,
    tags: ["Sunset", "Pastel", "Tempo Run", "Mesh"],
    photographer: "Sarah Jenkins",
    location: "Williamsburg, Brooklyn",
    likes: 415,
  },
  {
    id: "gal-women-4",
    title: "Studio Rebound — Aerodynamic Flow",
    category: "WOMEN",
    imageUrl: "https://images.unsplash.com/photo-1575537302964-96cd47c06b1b?w=1200&q=85",
    description: "Sculpted lateral support shoe crafted for high-intensity studio agility drills, HIIT cross-training, and contemporary dance.",
    shoeModel: "VELOCE STUDIO FLEX NITRO",
    link: "/category/sneakers",
    order: 4,
    tags: ["Studio", "Agility", "Training", "Dynamic"],
    photographer: "Chloe Dubois",
    location: "SoHo Dance Lab, NYC",
    likes: 198,
  },

  // =================== MEN'S COLLECTION ===================
  {
    id: "gal-men-1",
    title: "Tokyo Underground — Carbon Stride High",
    category: "MEN",
    imageUrl: "https://images.unsplash.com/photo-1552346154-21d32810aba3?w=1200&q=85",
    description: "Harajuku cyberpunk styling with our high-traction carbon runner. Engineered for midnight city exploration and neon aesthetics.",
    shoeModel: "VELOCE NITRO-CARBON 01",
    link: "/category/sneakers",
    order: 5,
    tags: ["Cyberpunk", "Tokyo", "High Traction", "Streetwear"],
    photographer: "Kenji Takahashi",
    location: "Shibuya, Tokyo",
    likes: 520,
  },
  {
    id: "gal-men-2",
    title: "Berlin Marathon Track Day — Speed Propulsion",
    category: "MEN",
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1200&q=85",
    description: "Sub-2 hour marathon championship silhouette featuring dual curved carbon plates and supercritical rebound foam.",
    shoeModel: "VELOCE MARATHON RACER X",
    link: "/category/running",
    order: 6,
    tags: ["Marathon", "Championship", "Carbon Plate", "Record Pace"],
    photographer: "Lukas Weber",
    location: "Tiergarten, Berlin",
    likes: 467,
  },
  {
    id: "gal-men-3",
    title: "Tuscan Heritage — Burnished Calfskin Loafer",
    category: "MEN",
    imageUrl: "https://images.unsplash.com/photo-1512374382149-233c42b66137?w=1200&q=85",
    description: "Full-grain French calfskin hand-burnished in Florence. Goodyear welted with Vibram lug inserts for unrivaled boardroom presence.",
    shoeModel: "VELOCE TUSCAN ATELIER DERBY",
    link: "/category/boots",
    order: 7,
    tags: ["Artisanal", "Florence", "Calfskin", "Formal"],
    photographer: "Gianni Romano",
    location: "Florence, Italy",
    likes: 312,
  },
  {
    id: "gal-men-4",
    title: "Alpine Trailhead — All-Terrain Rugged V2",
    category: "MEN",
    imageUrl: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=1200&q=85",
    description: "GORE-TEX waterproof membrane paired with deep lugged Vibram Megagrip traction for extreme technical mountain descents.",
    shoeModel: "VELOCE ALL-TERRAIN V2",
    link: "/category/sneakers",
    order: 8,
    tags: ["Outdoor", "Gore-Tex", "Vibram", "Mountain"],
    photographer: "Marcus Vance",
    location: "Zermatt, Switzerland",
    likes: 275,
  },

  // =================== KIDS & CHILDREN COLLECTION ===================
  {
    id: "gal-kids-1",
    title: "Junior Champions — Dynamic Flex Stride",
    category: "KIDS",
    imageUrl: "https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=1200&q=85",
    description: "Designed specifically for growing athletes. Features ergonomic arch support, flexible groove outsoles, and durable scuff-resistant toe guards.",
    shoeModel: "VELOCE JUNIOR FLEX TRAINER",
    link: "/category/sneakers",
    order: 9,
    tags: ["Junior", "Growing Athletes", "Flexible", "Kids"],
    photographer: "Amanda Cruz",
    location: "Olympic Youth Academy",
    likes: 388,
  },
  {
    id: "gal-kids-2",
    title: "Urban Playground — Neon Bounce Junior",
    category: "KIDS",
    imageUrl: "https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=1200&q=85",
    description: "Vibrant high-energy cushioning with quick-lock speed laces. Keeps active kids fast, comfortable, and visible with 360° reflective details.",
    shoeModel: "VELOCE NEO-BOUNCE KIDS",
    link: "/category/running",
    order: 10,
    tags: ["Neon", "Speed Laces", "Playground", "Reflective"],
    photographer: "David Miller",
    location: "Central Park Track, NYC",
    likes: 295,
  },
  {
    id: "gal-kids-3",
    title: "Adventure Ready — Mini Trail Explorer",
    category: "KIDS",
    imageUrl: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=1200&q=85",
    description: "Rugged yet featherlight trail shoe for school adventures, camping trips, and weekend park runs. Reinforced water-resistant upper.",
    shoeModel: "VELOCE MINI ALL-TERRAIN",
    link: "/category/sneakers",
    order: 11,
    tags: ["Adventure", "Rugged", "Lightweight", "Water-Resistant"],
    photographer: "Sofia Morales",
    location: "Aspen Youth Camp",
    likes: 240,
  },
  {
    id: "gal-kids-4",
    title: "Heritage Retro High — Junior Court Edition",
    category: "KIDS",
    imageUrl: "https://images.unsplash.com/photo-1511556532299-8f662fc26c06?w=1200&q=85",
    description: "Classic basketball court inspired high-top crafted with soft eco-leather, padded ankle collars, and non-marking gum soles.",
    shoeModel: "VELOCE RETRO MINI HIGH",
    link: "/category/lifestyle",
    order: 12,
    tags: ["High Top", "Eco Leather", "Court", "Heritage"],
    photographer: "Kenji Takahashi",
    location: "Venice Beach Courts, LA",
    likes: 310,
  },
];
